### ISSUE TITLE
[Glitch]Play button not working except for movies already in my home screen widgets

### ISSUE THREAD

**Issue by onlytanmoy** [nfm886/skin.arctic.zephyr.2.resurrection.mod#9]
Hiya, please see this screen record

https://www.veed.io/download/495f3385-dcae-4122-b5a2-07e817e2c266

At 1:02 timeline when I click on Play button nothing happens, the poster just stays there.
Let me know if you need more details around the navigation I am doing but basically play button does not work for other movies the cast is part of or other movies by same director etc. It is working for the movies that are part of my home screen widgets.
I am in version 0.3.4 of AZ2R skin.

**Comment by nfm886** [comment]
Hey!
I'm aware of this issue. The problem is, it does not throws any errors so it's hard to investigate.
I will try to fix as soon as it's possible. But I'm not sure when it will be done. I had some tries on fixing it but without error log it's hard.

**Comment by onlytanmoy** [comment]
Yeah, it gets difficult to understand the root cause without any error message or log. And no rush, take your time. You are doing a great work so cheers to that 👍

**Comment by onlytanmoy** [comment]
Hi mate @nfm886 good news, looks like this has been fixed, just tested with the new zip you gave today 🥇 

I noticed one glitch though, please refer the screen record.
https://www.veed.io/download/d8a4a4f4-862b-48ae-a720-3510791ef2cb

When I stop the movie, it shows me a black screen with weather & time displayed on top right corner and then when I press back button of the remote it brings me back to the home screen. Personally I don't mind to click  back button but thought of bringing to your notice :) let me know your thoughts.

**Comment by nfm886** [comment]
Hmm.. That's interesting but it looks like it's partially fixed ^^
Will do some more fixes to it later :)

**Comment by onlytanmoy** [comment]
Please check this screen record using AZ - Reloaded skin. 
https://imgur.com/a/zn7HsDS

I was wondering if it will be possible to have a fanart/artwork section like this in AZ2R skin.

**Comment by nfm886** [comment]
We have this already: https://streamable.com/japncj :)

**Comment by onlytanmoy** [comment]
😄 Indeed, guess I was lazy to scroll at the very bottom to check that out before, your video helped :) cheers!

**Comment by onlytanmoy** [comment]
On a diff note, are you using any maintenance add-on for Kodi for clearing cache etc., something to speed up Kodi really? I am using Shield Pro 2019 with fibre broadband (avg. speed 170 Mbps) but do feel it takes time to fetch info like Cast, similar movies etc.

**Comment by nfm886** [comment]
Nope. Just a pure Kodi basically with some addons like YouTube or Netflix.
My next goal is to improve performance on DialogVideoInfo if it's possible. I have some ideas but they need to be implemented :P

**Comment by nfm886** [comment]
Hey!
That took a bit of time, but I think it's sorted out. Would you like to do some tests?
Please download this zip file: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip
I did it a bit tricky. Now there is no more trailer button, instead there is one Play button, which works like that:
If it recognize movie from local library, it will play it, if it recognize source comes from plugin, it will play trailer. Maybe it's not best solution but for now, could not figure out anything better. Maybe I will bring back trailer button as an alternative. Because now you can't play trailer and play movie from DialogVideoInfo but you can play one of them.
Also please test if local movies/tv shows works playing them from DialogVideoInfo and of course test some trailers from plugins - tmdb helper, etc.

**Comment by onlytanmoy** [comment]
Good things take time so no worries on that front.
I just now tested. I don't do local videos only streaming via addons.
Please have play button in DialogVideoInfo play movies only and NOT trailers.
If we can't have both trailer & play then bring back the trailer button, remove the play button. The Trakt button is there so if I like the trailer I can add to my Trakt list.

**Comment by onlytanmoy** [comment]
@nfm886 can you please roll back to this version? see below my comments from 6 days back

_Hi mate @nfm886 good news, looks like this has been fixed, just tested with the new zip you gave today 🥇

I noticed one glitch though, please refer the screen record.
https://www.veed.io/download/d8a4a4f4-862b-48ae-a720-3510791ef2cb

When I stop the movie, it shows me a black screen with weather & time displayed on top right corner and then when I press back button of the remote it brings me back to the home screen. Personally I don't mind to click back button but thought of bringing to your notice :) let me know your thoughts._

**Comment by nfm886** [comment]
Ok, thanks for  your feedback!
I will bring back previous behavior on the play button (or maybe with some tweaks) and bring back trailer button. :)
So "glitch" you mentioned is not fixed in this version?

**Comment by onlytanmoy** [comment]
Yes please, bring back the previous behaviour on play button and the trailer button separately.
Like I said before, the only minor issue I observed with the version you gave me 6 days ago is when I stop the movie, it shows me a black screen with weather & time displayed on top right corner and then when I press back button of the remote it brings me back to the home screen. I am totally fine with this, extra button click is no big deal. Once this behaviour is back, I will be super happy and close this ticket :)

**Comment by nfm886** [comment]
Ok, please test this now: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip and give me a feedback what happening :P

**Comment by onlytanmoy** [comment]
OK, tried the new zip, 2 observations/feedback as of now:
a. Clicking on other movie from DialogVideoInfo takes quite a long time :( see the screen capture video below
b. Clicking on Play button from DialogVideoInfo does nothing!

https://www.veed.io/download/e4d8cc15-a907-42be-8324-ead551261b42

**Comment by nfm886** [comment]
What add-on you are using? I need to reproduce this on my machine.

**Comment by nfm886** [comment]
Meanwhile please test this zip file: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip

**Comment by onlytanmoy** [comment]
I am using TMDb Helper add-on so that I can choose players/addons like Venom, Fen, Seren etc. to scrape the file when I hit the Play button, see below screenshot

![image](https://user-images.githubusercontent.com/48493659/122677396-014f9300-d1da-11eb-9023-65a703a0c89c.png)

**Comment by nfm886** [comment]
Does it works now?

**Comment by onlytanmoy** [comment]
Unfortunately not, I don't see any change with this new zip.
Point a is a real bummer, lonngg wait.
Play button does nothing, shows blank Info screen (as you saw in the video I posted earlier).
Can you share the zip from 6 days back? I suppose that was the last working version.

**Comment by nfm886** [comment]
Try this: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/6deba4c36201c6e88a1ce15b263d9b73441fe2b4.zip
This is before my today's changes. It should works since I did not mess with it before until today.

**Comment by nfm886** [comment]
This is 0.3.8 from 7 days before: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/099c8a2f26eec94a7a724a702215ff3ae366f874.zip but I'm sure previous archive from today's morning should works just fine.

**Comment by onlytanmoy** [comment]
> Try this: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/6deba4c36201c6e88a1ce15b263d9b73441fe2b4.zip
> This is before my today's changes. It should works since I did not mess with it before until today.
Tried this one, I am on version 0.4.4 of AZ2R skin, point a seems to have improved a lot, phew :)
b & c still issue persists, please see screen record
https://www.veed.io/download/b3636cce-3fdf-474e-b7fe-53cfeec8a399

**Comment by nfm886** [comment]
Are you using themoviedb helper from official repository? It should be on version 4.3.0

**Comment by onlytanmoy** [comment]
I am using the one from jurialmunkey, version 4.3.9
![Kodi_20210620_155338](https://user-images.githubusercontent.com/48493659/122678695-c6e8f480-d1df-11eb-8938-6f1ca6a7a123.png)

**Comment by nfm886** [comment]
There is 4.3.10 in jurialmunkey's repository. Please update it. I was using 4.3.0 before but tried this one from JM repo and it seems it does not load too long. Please see this screen capture: https://streamable.com/qszned

**Comment by nfm886** [comment]
Also trailer button works just fine with latest fix: https://streamable.com/uv1q4g

**Comment by onlytanmoy** [comment]
Strange, I never got update available notification :) manually updated to v4.3.10 now, thanks.
Trailer works fine for the movies that are already in my home screen widgets, it is not working for similar/related movies in the next screen, hope you got me.

**Comment by nfm886** [comment]
I see :) We are here to fix those problems I hope ^^
Please make sure you have embuary helper installed. Then please try latest main version: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip
Trailers should works, play button should works too: https://streamable.com/rvlupj

**Comment by onlytanmoy** [comment]
:) thanks for your patience mate.
Yes I have embuary helper installed, will try the latest version now and report back.
![Kodi_20210620_161918](https://user-images.githubusercontent.com/48493659/122679578-5a6ff480-d1e3-11eb-94b2-671a09b62ff8.png)
Did you notice the text overlap in the screenshot? No need to fix this as hardly used, just bringing to your notice.

**Comment by nfm886** [comment]
Not happens to me: https://imgur.com/1R80grQ ^^ Please try do enable/disable blur. Maybe this will fix this. However I think you have messed a lot of with your build^^

**Comment by onlytanmoy** [comment]
Tested with the latest version, trailer working fine now :) However, play button still not working.
Captured the screen for your reference
https://www.veed.io/download/535b1844-5e18-4d6e-bfa8-891f738610cb

**Comment by nfm886** [comment]
Ok, I'm trying to fix it. Will be back with any changes :)

**Comment by onlytanmoy** [comment]
No rush mate, this can wait. Please enjoy your Sunday 🍻

**Comment by nfm886** [comment]
Could you please test latest version: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip ?
I made some changes to it. Just curious how it will react with your build. Please record a screen capture :)

**Comment by onlytanmoy** [comment]
Please see screen record video with latest version. Trailer working fine, play does not.
https://www.veed.io/download/e5dff24c-643a-4f4d-a336-7440209d8011

You know what I will uninstall Kodi 19 and setup all new just with AZ2R skin and some basic addons like Venom, Fen, TMDb helper and then see how that goes :) fingers crossed.

I will be away from system for an hour so expect delay in response :)

**Comment by onlytanmoy** [comment]
@nfm886 I am back :) sent you a DM in Reddit, kindly check.

**Comment by nfm886** [comment]
After a long day, I think we sorted it out! :)
Will be pushed in today's update. Many thanks to @onlytanmoy for his testing!

**Comment by onlytanmoy** [comment]
Yep, you finally nailed it mate. Hats off to your relentless efforts, much appreciated.
